services:
  bot:
    container_name: "HamsterKombatBot"
    build:
      context: .
    logging:
      driver: "json-file"
      options:
        max-file: 5
        max-size: 100m
    stop_signal: SIGINT
    restart: unless-stopped
    command: "python3 main.py -a 2"
    volumes:
      - ./sessions:/app/sessions
      - ./profiles.json:/app/profiles.json
    env_file:
      - .env
